---
title: "R Notebook"
output: html_notebook
---

```{r}
require(bbplot)
require(ggplot2)
require(lubridate)
require(ggmap)
require(cluster)
require(dplyr)
require(prophet)
require(reshape2)
```

```{r}
df <- read.csv("https://earthquake.usgs.gov/fdsnws/event/1/query?format=csv&starttime=2019-12-20&endtime=2020-01-19&latitude=17.949&longitude=-66.851&maxradiuskm=50")
df$dateTime <- as.POSIXct(df$time, format="%Y-%m-%dT%H:%M:%OS", tz="GMT")
# Change the time zone
df$dateTime <- with_tz(df$dateTime, "America/Puerto_Rico")
df$date <- date(df$dateTime)
df <- df[df$mag > 0,]
```


```{r}
events.per.day <- df %>%
  select(mag, date) %>%
  group_by(date) %>%
  summarise(n = n())
```


```{r}
summary(events.per.day)
```


```{r}
mean(df[df$date == '2019-12-31',]$mag)
```


```{r}
print(summary(df$mag))
print(sd(df$mag))
```


```{r}
p <- ggplot(df, aes(x=mag)) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept=mean(df$mag)) +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), "cm"),
        axis.text.x = element_text(hjust = 1)) +
  ggtitle("Histogram of the magnitudes", subtitle = "From 21-12-2019 to 19-01-2020") +
  xlab("Magnitude")
print(p)
```


```{r}
p <- ggplot(df, aes(y=mag)) +
  geom_boxplot()+
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0, 1.0, 1.0, 0.5), "cm"),
        axis.text.x = element_text(hjust = 1)) +
  ggtitle("Boxplot of the magnitudes", subtitle = "From 21-12-2019 to 19-01-2020") +
  ylab("Magnitude")
print(p)
```


```{r, message=FALSE}
p <- ggplot(data=df ,aes(x=dateTime,y=mag)) + 
  geom_point(size = df$mag, alpha = 0.5) +
  geom_smooth() +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), "cm"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) +
  xlab('Date') + ylab('Magnitude') +
  scale_x_datetime(date_breaks = "3 day") +
  ggtitle("The magnitude value of Puerto Rico's earthquakes", subtitle = "From 21-12-2019 to 19-01-2020")
print(p)
```

```{r}
map <- get_googlemap(center=c(-66.7707549, 17.9472521), zoom = 10, maptype = 'roadmap', size = c(640, 640), scale = 2)
```


```{r}
p <- map %>% ggmap() +
  geom_point(data = df, 
             aes(x = longitude, y = latitude), size = df$mag, alpha = 0.5) +
  stat_density2d(data=df, aes(x=longitude, y=latitude, fill = stat(level), alpha=..level..),
                 geom='polygon') +
  scale_color_brewer(palette='Set1')+
  theme(legend.position = 'none',
        plot.title = element_text(size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(1.0,1.5,1.0,0.5), 'cm')) +
  xlab('Longitude') + ylab('Latitude') +
  ggtitle("Puerto Rico's Earthquakes", subtitle = "From 21-12-2019 to 19-01-2020")
print(p)
```

```{r}
mean(df$latitude)
mean(df$longitude)
```

```{r}
trend <- read.csv("data/trend.csv")
max.per.day$date <- as.character(max.per.day$date)
colnames(max.per.day) <- c('date', 'max_magnitude')
trend <- merge(trend, max.per.day, by = 'date')
trend.wide <- melt(trend, id.vars = c("date"))
trend.wide$date <- as.Date(trend.wide$date)
```

```{r}
p <- ggplot(data=trend.wide ,aes(x=date,y=value, color = variable)) + 
  geom_line() +
  bbc_style() +
  theme(axis.title = element_text(size = 18), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), "cm"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) +
  xlab('Date') + ylab('Magnitude') +
  scale_x_date(date_breaks = "3 days") + 
  scale_y_continuous(sec.axis= sec_axis(~.*1, name="trend (log scale)"), trans = "log10") +
  ggtitle("Google Trends' trend of the query \"Puerto Rico\" and the magnitudes", subtitle = "21-12-2019 to 17-01-2020")
print(p)
```

```{r}
cor(trend$trend, trend$max_magnitude)
```


